name: Rust CI

on:
  push:
    branches: [main, feature]
  pull_request:
    branches: [main, feature]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose

  build-test-artifacts:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Build and archive tests
        run: cargo nextest archive --archive-file nextest-archive.tar.zst
      - name: Upload archive to workflow
        uses: actions/upload-artifact@v3
        with:
          name: nextest-archive
          path: nextest-archive.tar.zst
      - name: Run tests
        run: cargo test --verbose

  run-tests:
    name: Run tests with nextest
    runs-on: ubuntu-latest
    needs: build-test-artifacts
    steps:
      - uses: actions/checkout@v2
        with:
          # By default actions/checkout checks out a merge commit. Check out the PR head instead.
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
      - run: mkdir -p ~/.cargo/bin
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Download archive
        uses: actions/download-artifact@v3
        with:
          name: nextest-archive
      - name: Run tests
        run: |
          ~/.cargo/bin/cargo-nextest nextest run --archive-file nextest-archive.tar.zst

  lint:
    name: Run Linter (clippy)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: cargo clippy -- -D warnings

  format:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run cargo fmt
        run: cargo fmt -- --check
